# Generated by Django 3.1.1 on 2020-10-10 19:34

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20201007_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
