# Generated by Django 3.1.1 on 2020-10-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_car_order_user_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_order',
            old_name='user_account',
            new_name='user_profile',
        ),
    ]
