# Generated by Django 3.1.1 on 2020-10-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='car_review',
            field=models.TextField(),
        ),
    ]
