# Generated by Django 3.1.1 on 2020-10-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20201025_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='fuel_type',
            new_name='advantage',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='transmission',
            new_name='disadvantage',
        ),
    ]
