# Generated by Django 3.1.1 on 2020-09-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
