# Generated by Django 3.1.1 on 2020-11-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200914_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='for_sale',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
